name: deploy

on:
  push:
    branches: [ staging ]

concurrency: production_environment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Add Composer auth credentials for Backpack
        run: composer config http-basic.backpackforlaravel.com "${{ secrets.BACKPACK_USERNAME }}" "${{ secrets.BACKPACK_PASSWORD }}" --global

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Deploy
        uses: deployphp/action@v1
        with:
          # Output of `cat ~/.ssh/id_rsa`.
          private-key: ${{ secrets.PRIVATE_KEY }}
          # Output of `ssh-keyscan [VPS hostname]`.
          # Copy just the line where the SSH public key matches the PRIVATE_KEY
          known-hosts: ${{ secrets.KNOWN_HOSTS }}
          dep: deploy staging
